name: nize_gallery
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  share_plus: ^7.1.0
  permission_handler: ^10.2.1
  file_manager: ^1.0.2
  path_provider: ^2.0.15
  open_file: ^3.3.2
  flutter_riverpod: ^1.0.4
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2
  google_fonts: ^6.1.0
  encrypt: ^5.0.1
  pdf: ^3.10.4
  printing: ^5.11.0
  # get: ^4.6.5
  # video_thumbnail: ^0.5.3
 

  
  # photo_gallery: ^2.0.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: GalanoGrotesque
      fonts:
        - asset: font/GalanoGrotesqueAltBold.otf
        - asset: font/GalanoGrotesqueAltMedium.otf
        - asset: font/GalanoGrotesqueAltRegular.otf
        - asset: font/GalanoGrotesqueAltSemiBold.otf
        - asset: font/GalanoGrotesqueBold.otf
        - asset: font/GalanoGrotesqueMedium.otf
        - asset: font/GalanoGrotesqueRegular.otf
        - asset: font/GalanoGrotesqueSemiBold.otf
        

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
